--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaisukeDaisukeTeam/FdLibrary
build-by-default: true
branches:
- main
projects: 
  FdLibrary:
    libs:
      - src: muqsit/invmenu/InvMenu
        version: ^4.3.8
      - src: DaisukeDaisukeTeam/libNpcDialogue/libNpcDialogue
        version: ^1.0.0
      - src: pjz9n-pm-pl/libi18n/libi18n
        version: ^1.0.3
      - src: CortexPE/Commando/Commando
        version: ^2.1.1
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.0
      - src: DaisukeDaisukeTeam/Flowy/Flowy
        version: ^0.1.0
      - src: DaisukeDaisukeTeam/Flowy/Standard
        version: ^0.1.0
...
