--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaisukeDaisukeTeam/FdLibrary
build-by-default: true
branches:
- main
projects: 
  FdLibrary:
    libs:
      - src: pjz9n-pm-pl/libi18n/libi18n
        version: ^1.0.3
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
      - src: SOF3/await-generator/await-generator
        version: ^3.4.3
      - src: SOF3/await-std/await-std
        version: 0.2.0
...
